# @format

name: puthagam_podcaster
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  record: ^4.4.0
  path_provider: ^2.0.1
  audioplayers: ^1.0.1
  flutter_fadein: 2.0.0
  velocity_x: 3.5.1
  get_storage: ^2.0.3
  retrofit: ^3.0.1
  intl: 0.17.0
  audio_waveforms: ^0.1.5+1
  lottie: 1.4.3
  just_audio: ^0.9.29
  flutter:
    sdk: flutter
  flutter_rtmp_streamer:
    git:
      url: https://github.com/kuzalex2/flutter_rtmp_streamer.git
      ref: develop
  audio_picker:
    git:
      url: https://github.com/himanshukharemipl/audio_picker.git
      ref: master

dev_dependencies:
  flutter_lints: ^2.0.0
  build_runner: any
  flutter_launcher_icons: "^0.10.0"
  flutter_gen_runner: any
  retrofit_generator: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#ffffff"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
